### ISSUE TITLE
Assess current feedback forms

### ISSUE THREAD

**Issue by bas-ie** [dev-academy-programme/feedbacker#10]
How can we improve the consistency of the forms? For example, use dropdowns to restrict cohort names to a predefined set.

**Comment by richchurcher** [comment]
Ongoing. Note one draft for Phase 0 at: https://docs.google.com/forms/d/1iMTTM6fehsvW4efp_w1cxVEarQNx4YkIiniLGyD170Q/edit

**Comment by richchurcher** [comment]
Draft/playground for Bootcamp: https://docs.google.com/forms/d/e/1FAIpQLScQpRmuxW9_01B8pyyBj69fDV_vnVYWBbq-j0k6ClpvK81s1Q/viewform

**Comment by richchurcher** [comment]
Phase 0 complete enough to work with.
