### ISSUE TITLE
Mini-spike: what does bottom-up look like for this problem set?

### ISSUE THREAD

**Issue by bas-ie** [dev-academy-programme/feedbacker#8]
I really liked the "bottom-up" testing approach they used at the Global Day of Code recently. Be cool to see how it works here. There are a lot of interdependent parts to the data... I'd like to understand how we could isolate them so that if the dataset changes, and it will, we're resilient.

**Comment by richchurcher** [comment]
I think it may start with a question (from the feedback form). If we say questions are made up of question text, answer type and content (which may need translation depending on type), then being able to take a question and update central totals/series for graphing is bottom up... obtaining an API response and displaying it is top-down.

Maybe the simplest/smallest operation is taking the question title and chunking the number out of it (1.2/4.4) into a 'question' object. Or updating a central totals object based on a yes/no answer...
